"""initial schema — all 17 tables

Revision ID: 5366883fd5ac
Revises: 
Create Date: 2026-09-10 18:59:33.006164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5366883fd5ac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('tier', sa.String(length=30), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('instagram_handle', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('style_tags', sa.JSON(), nullable=True),
    sa.Column('typical_price_min', sa.Integer(), nullable=True),
    sa.Column('typical_price_max', sa.Integer(), nullable=True),
    sa.Column('modesty_score', sa.Float(), nullable=True),
    sa.Column('eastern_western_ratio', sa.Float(), nullable=True),
    sa.Column('target_age_min', sa.Integer(), nullable=True),
    sa.Column('target_age_max', sa.Integer(), nullable=True),
    sa.Column('data_source', sa.String(length=50), nullable=False),
    sa.Column('data_license', sa.String(length=50), nullable=False),
    sa.Column('commercial_use_ok', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('data_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('robots_checked', sa.Boolean(), nullable=False),
    sa.Column('tos_reviewed', sa.Boolean(), nullable=False),
    sa.Column('scraping_permitted', sa.Boolean(), nullable=False),
    sa.Column('commercial_use_ok', sa.Boolean(), nullable=False),
    sa.Column('api_available', sa.Boolean(), nullable=False),
    sa.Column('requires_auth', sa.Boolean(), nullable=False),
    sa.Column('rate_limit', sa.String(length=100), nullable=True),
    sa.Column('attribution_required', sa.Boolean(), nullable=False),
    sa.Column('attribution_text', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('trends',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('season', sa.String(length=20), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('geographic_scope', sa.String(length=30), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('brand_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('brand_id', sa.String(length=36), nullable=False),
    sa.Column('season', sa.String(length=20), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('common_colors', sa.JSON(), nullable=True),
    sa.Column('common_silhouettes', sa.JSON(), nullable=True),
    sa.Column('common_fabrics', sa.JSON(), nullable=True),
    sa.Column('common_occasions', sa.JSON(), nullable=True),
    sa.Column('trend_alignment', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forecasts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trend_id', sa.String(length=36), nullable=True),
    sa.Column('forecast_name', sa.String(length=200), nullable=False),
    sa.Column('forecast_type', sa.String(length=50), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('confidence_level', sa.String(length=10), nullable=False),
    sa.Column('forecast_horizon', sa.String(length=30), nullable=False),
    sa.Column('supporting_signals', sa.JSON(), nullable=True),
    sa.Column('uncertainty_notes', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=10), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trend_id'], ['trends.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('garments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('subcategory', sa.String(length=50), nullable=True),
    sa.Column('colors', sa.JSON(), nullable=True),
    sa.Column('fabric', sa.String(length=50), nullable=True),
    sa.Column('silhouette', sa.String(length=50), nullable=True),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('image_hash', sa.String(length=64), nullable=True),
    sa.Column('vision_attributes', sa.JSON(), nullable=True),
    sa.Column('aesthetic_tags', sa.JSON(), nullable=True),
    sa.Column('modesty_level', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('interaction_type', sa.String(length=20), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outfits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('occasion', sa.String(length=50), nullable=False),
    sa.Column('season', sa.String(length=20), nullable=False),
    sa.Column('components', sa.JSON(), nullable=False),
    sa.Column('total_price', sa.Integer(), nullable=False),
    sa.Column('modesty_level', sa.Integer(), nullable=False),
    sa.Column('aesthetic_tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('brand_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('garment_family', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subcategory', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('original_price', sa.Integer(), nullable=True),
    sa.Column('fabric', sa.String(length=50), nullable=True),
    sa.Column('colors', sa.JSON(), nullable=True),
    sa.Column('silhouette', sa.String(length=50), nullable=True),
    sa.Column('neckline', sa.String(length=50), nullable=True),
    sa.Column('sleeve', sa.String(length=50), nullable=True),
    sa.Column('embellishment', sa.String(length=50), nullable=True),
    sa.Column('modesty_level', sa.Integer(), nullable=False),
    sa.Column('occasion_tags', sa.JSON(), nullable=True),
    sa.Column('season_tags', sa.JSON(), nullable=True),
    sa.Column('aesthetic_tags', sa.JSON(), nullable=True),
    sa.Column('size_range', sa.JSON(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('product_url', sa.String(length=500), nullable=True),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.Column('data_source', sa.String(length=50), nullable=False),
    sa.Column('data_license', sa.String(length=50), nullable=False),
    sa.Column('commercial_use_ok', sa.Boolean(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.Column('last_verified', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('style_dna',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('minimal', sa.Float(), nullable=False),
    sa.Column('maximalist', sa.Float(), nullable=False),
    sa.Column('feminine', sa.Float(), nullable=False),
    sa.Column('androgynous', sa.Float(), nullable=False),
    sa.Column('traditional', sa.Float(), nullable=False),
    sa.Column('contemporary', sa.Float(), nullable=False),
    sa.Column('romantic', sa.Float(), nullable=False),
    sa.Column('edgy', sa.Float(), nullable=False),
    sa.Column('streetwear', sa.Float(), nullable=False),
    sa.Column('classic', sa.Float(), nullable=False),
    sa.Column('bohemian', sa.Float(), nullable=False),
    sa.Column('eastern_affinity', sa.Float(), nullable=False),
    sa.Column('modesty_score', sa.Float(), nullable=False),
    sa.Column('interaction_count', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('style_preferences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('pref_type', sa.String(length=50), nullable=False),
    sa.Column('pref_value', sa.String(length=200), nullable=False),
    sa.Column('sentiment', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('style_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('lifestyle', sa.String(length=200), nullable=True),
    sa.Column('budget_min', sa.Integer(), nullable=False),
    sa.Column('budget_max', sa.Integer(), nullable=False),
    sa.Column('modesty_level', sa.Integer(), nullable=False),
    sa.Column('eastern_western_pref', sa.Float(), nullable=False),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('enable_body_recommendations', sa.Boolean(), nullable=False),
    sa.Column('preferred_aesthetics', sa.JSON(), nullable=True),
    sa.Column('preferred_colors', sa.JSON(), nullable=True),
    sa.Column('disliked_colors', sa.JSON(), nullable=True),
    sa.Column('preferred_occasions', sa.JSON(), nullable=True),
    sa.Column('preferred_brands', sa.JSON(), nullable=True),
    sa.Column('disliked_brands', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('trend_scores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trend_id', sa.String(length=36), nullable=False),
    sa.Column('popularity_score', sa.Float(), nullable=False),
    sa.Column('growth_score', sa.Float(), nullable=False),
    sa.Column('cross_brand_score', sa.Float(), nullable=False),
    sa.Column('search_score', sa.Float(), nullable=False),
    sa.Column('seasonal_score', sa.Float(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('signal_count', sa.Integer(), nullable=False),
    sa.Column('score_version', sa.String(length=10), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trend_id'], ['trends.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trend_signals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trend_id', sa.String(length=36), nullable=False),
    sa.Column('signal_type', sa.String(length=50), nullable=False),
    sa.Column('signal_value', sa.Float(), nullable=False),
    sa.Column('signal_date', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trend_id'], ['trends.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('outfit_id', sa.String(length=36), nullable=False),
    sa.Column('occasion', sa.String(length=50), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('style_match', sa.Float(), nullable=False),
    sa.Column('budget_match', sa.Float(), nullable=False),
    sa.Column('modesty_match', sa.Float(), nullable=False),
    sa.Column('trend_match', sa.Float(), nullable=False),
    sa.Column('critic_passed', sa.Boolean(), nullable=False),
    sa.Column('critic_notes', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfits.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendations')
    op.drop_table('price_history')
    op.drop_table('trend_signals')
    op.drop_table('trend_scores')
    op.drop_table('style_profiles')
    op.drop_table('style_preferences')
    op.drop_table('style_dna')
    op.drop_table('products')
    op.drop_table('outfits')
    op.drop_table('interactions')
    op.drop_table('garments')
    op.drop_table('forecasts')
    op.drop_table('brand_profiles')
    op.drop_table('users')
    op.drop_table('trends')
    op.drop_table('data_sources')
    op.drop_table('brands')
    # ### end Alembic commands ###
