"""initial schema all 17 tables

Revision ID: 5febefa0e0c1
Revises: c84916ac5bc4
Create Date: 2026-09-10 19:00:59.723180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5febefa0e0c1'
down_revision: Union[str, Sequence[str], None] = 'c84916ac5bc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
